-- AdMate Compass schema v1
-- Scope: schema-only preparation for Compass RAG/document indexes.
-- Gate 3 confirmed source document_chunks and ollama_document_chunks use vector(1024).
-- v1 explicitly excludes policy archive table candidates with different dimensions.
-- Do not run until Gate 4 schema-only execution is separately approved.

create schema if not exists compass;

create extension if not exists vector;
create extension if not exists "uuid-ossp";
create extension if not exists pgcrypto;

do $$
begin
  if not exists (
    select 1
    from pg_type t
    join pg_namespace n on n.oid = t.typnamespace
    where n.nspname = 'compass'
      and t.typname = 'vendor_enum'
  ) then
    create type compass.vendor_enum as enum ('META', 'GOOGLE', 'NAVER', 'KAKAO', 'X', 'TIKTOK');
  end if;
end $$;

create table if not exists compass.documents (
  id text primary key,
  title text not null,
  content text default '',
  type text not null check (type = any (array['file', 'url', 'pdf', 'docx', 'txt'])),
  document_url text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  chunk_count integer default 0,
  status text default 'pending' check (status = any (array['pending', 'processing', 'completed', 'indexed', 'failed'])),
  url text,
  size bigint default 0,
  file_size bigint default 0,
  file_type text default '',
  source_vendor text default 'META',
  split_status jsonb,
  main_document_id text references compass.documents(id),
  original_file_name text,
  sanitized_file_name text,
  metadata jsonb default '{}'
);

create table if not exists compass.document_metadata (
  id text primary key references compass.documents(id),
  title text not null,
  type text not null check (type = any (array['pdf', 'docx', 'txt', 'url'])),
  size bigint not null,
  uploaded_at timestamp with time zone not null,
  processed_at timestamp with time zone,
  status text not null default 'pending' check (status = any (array['pending', 'processing', 'completed', 'failed'])),
  chunk_count integer default 0,
  embedding_count integer default 0,
  metadata jsonb default '{}',
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  original_file_name text
);

create table if not exists compass.document_chunks (
  id text primary key,
  document_id text not null,
  chunk_id integer not null,
  content text not null,
  -- Gate 3 confirmed source dimension: vector(1024).
  embedding vector(1024),
  created_at timestamp with time zone default now(),
  metadata jsonb,
  parent_chunk_id text,
  hierarchy_level text check (
    hierarchy_level = any (array['document', 'section', 'paragraph', 'sentence'])
    or hierarchy_level is null
  )
);

create table if not exists compass.ollama_document_chunks (
  id integer generated by default as identity primary key,
  document_id text not null,
  chunk_id text not null,
  content text not null,
  -- Gate 3 confirmed source dimension: vector(1024).
  embedding vector(1024),
  metadata jsonb default '{}',
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists compass.document_processing_logs (
  id integer generated by default as identity primary key,
  document_id text not null,
  step text not null,
  status text not null check (status = any (array['started', 'completed', 'failed'])),
  message text,
  error text,
  metadata jsonb default '{}',
  created_at timestamp with time zone default now()
);

create table if not exists compass.document_chunk_weights (
  id integer generated by default as identity primary key,
  document_id text not null,
  chunk_id text not null,
  positive_feedback_count integer default 0,
  negative_feedback_count integer default 0,
  weight_score numeric default 1.0,
  last_updated timestamp with time zone default now(),
  created_at timestamp with time zone default now()
);

create table if not exists compass.processing_jobs (
  id uuid primary key default gen_random_uuid(),
  document_id text references compass.documents(id),
  job_type text not null check (job_type = any (array['OCR', 'PDF_PARSE', 'DOCX_PARSE', 'CRAWL', 'CRAWL_SEED', 'EMBEDDING', 'CHUNK_PROCESS', 'DISCOVER_URLS'])),
  status text not null default 'queued' check (status = any (array['queued', 'processing', 'completed', 'failed', 'cancelled', 'retrying'])),
  priority integer not null default 5 check (priority >= 1 and priority <= 10),
  attempts integer not null default 0,
  max_attempts integer not null default 3,
  error text,
  payload jsonb default '{}',
  result jsonb,
  scheduled_at timestamp with time zone default now(),
  started_at timestamp with time zone,
  finished_at timestamp with time zone,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists compass.document_splits (
  id uuid primary key default gen_random_uuid(),
  document_id text not null references compass.documents(id),
  split_index integer not null,
  split_count integer not null,
  content text not null,
  start_char integer,
  end_char integer,
  page_number integer,
  section_title text,
  status text not null default 'pending' check (status = any (array['pending', 'processing', 'completed', 'failed'])),
  job_id uuid references compass.processing_jobs(id),
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists compass.discovered_urls (
  id uuid primary key default gen_random_uuid(),
  job_id uuid references compass.processing_jobs(id),
  url text not null,
  title text,
  depth integer not null,
  parent_url text,
  path jsonb default '[]',
  source text not null,
  selected boolean default false,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists compass.crawl_jobs (
  id uuid primary key default gen_random_uuid(),
  url text not null,
  status text default 'pending',
  pages_crawled integer default 0,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists compass.processing_metrics (
  id uuid primary key default gen_random_uuid(),
  job_id uuid,
  document_id text,
  bytes bigint,
  dl_ms integer,
  parse_ms integer,
  ocr_ms integer,
  emb_ms integer,
  total_ms integer,
  text_length integer,
  chunks integer,
  note text,
  created_at timestamp with time zone not null default now()
);

create table if not exists compass.url_templates (
  id integer generated by default as identity primary key,
  name character varying not null unique,
  urls text[] not null,
  vendor compass.vendor_enum default 'META',
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create index if not exists idx_compass_documents_status on compass.documents(status);
create index if not exists idx_compass_documents_created_at on compass.documents(created_at desc);
create index if not exists idx_compass_document_chunks_document_id on compass.document_chunks(document_id);
create index if not exists idx_compass_ollama_chunks_document_id on compass.ollama_document_chunks(document_id);
create index if not exists idx_compass_ollama_chunks_chunk_id on compass.ollama_document_chunks(chunk_id);
create index if not exists idx_compass_processing_jobs_document_id on compass.processing_jobs(document_id);
create index if not exists idx_compass_processing_jobs_status on compass.processing_jobs(status);

-- Create vector indexes after data load if source table is large.
-- Creating them before data import is valid but can slow large imports.
create index if not exists idx_compass_document_chunks_embedding
on compass.document_chunks
using ivfflat (embedding vector_cosine_ops)
with (lists = 100);

create index if not exists idx_compass_ollama_chunks_embedding
on compass.ollama_document_chunks
using ivfflat (embedding vector_cosine_ops)
with (lists = 100);

create or replace function compass.search_ollama_documents(
  query_embedding vector(1024),
  match_threshold float default 0.001,
  match_count int default 5
)
returns table (
  chunk_id text,
  content text,
  metadata jsonb,
  similarity float,
  embedding vector(1024)
)
language plpgsql
stable
as $$
begin
  return query
  select
    dc.chunk_id,
    dc.content,
    dc.metadata,
    1 - (dc.embedding <=> query_embedding) as similarity,
    dc.embedding
  from compass.ollama_document_chunks dc
  where dc.embedding is not null
    and 1 - (dc.embedding <=> query_embedding) > match_threshold
  order by dc.embedding <=> query_embedding
  limit match_count;
end;
$$;
