-- Compass Evidence Graph sidecar
-- Keeps official guide evidence and approved operational issue resolutions in a
-- graph-shaped layer that complements existing vector/keyword RAG retrieval.

CREATE SCHEMA IF NOT EXISTS compass;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS compass.evidence_nodes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  node_type text NOT NULL CHECK (
    node_type IN (
      'vendor',
      'source_document',
      'evidence_chunk',
      'policy_rule',
      'ad_object',
      'condition',
      'resolved_case',
      'tool',
      'data_requirement'
    )
  ),
  canonical_key text NOT NULL UNIQUE,
  label text NOT NULL,
  vendor text,
  aliases jsonb NOT NULL DEFAULT '[]'::jsonb,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS compass.resolved_cases (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id text,
  message_id text,
  feedback_id bigint,
  question text NOT NULL,
  issue_summary text NOT NULL,
  resolution_summary text NOT NULL,
  resolution_status text NOT NULL DEFAULT 'candidate' CHECK (
    resolution_status IN ('candidate', 'resolved', 'rejected', 'needs_official_check')
  ),
  resolved_by text,
  resolved_at timestamptz,
  approved_for_retrieval boolean NOT NULL DEFAULT false,
  sources jsonb NOT NULL DEFAULT '[]'::jsonb,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS compass.evidence_assertions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  claim_text text NOT NULL,
  claim_type text NOT NULL CHECK (
    claim_type IN (
      'definition',
      'requirement',
      'prohibition',
      'allowance',
      'limit',
      'procedure',
      'asset_spec',
      'resolved_issue',
      'risk',
      'setup_step'
    )
  ),
  source_kind text NOT NULL CHECK (source_kind IN ('official_doc', 'resolved_case')),
  source_document_id text,
  source_chunk_id text,
  case_id uuid REFERENCES compass.resolved_cases(id) ON DELETE SET NULL,
  excerpt text,
  source_url text,
  vendor text,
  evidence_decision text NOT NULL DEFAULT 'verified' CHECK (
    evidence_decision IN ('verified', 'weak', 'rejected')
  ),
  confidence numeric NOT NULL DEFAULT 0.8 CHECK (confidence >= 0 AND confidence <= 1),
  review_status text NOT NULL DEFAULT 'approved' CHECK (
    review_status IN ('candidate', 'approved', 'rejected', 'stale')
  ),
  valid_from timestamptz,
  valid_to timestamptz,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS compass.evidence_edges (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  subject_node_id uuid NOT NULL REFERENCES compass.evidence_nodes(id) ON DELETE CASCADE,
  predicate text NOT NULL CHECK (
    predicate IN (
      'MENTIONS',
      'SUPPORTED_BY',
      'APPLIES_TO',
      'HAS_CONDITION',
      'REQUIRES',
      'PROHIBITS',
      'ALLOWS',
      'LIMITS',
      'RESOLVED_BY',
      'CONFLICTS_WITH',
      'SUPERSEDES'
    )
  ),
  object_node_id uuid NOT NULL REFERENCES compass.evidence_nodes(id) ON DELETE CASCADE,
  evidence_assertion_id uuid REFERENCES compass.evidence_assertions(id) ON DELETE SET NULL,
  polarity text NOT NULL DEFAULT 'affirmative' CHECK (polarity IN ('affirmative', 'negative')),
  confidence numeric NOT NULL DEFAULT 0.8 CHECK (confidence >= 0 AND confidence <= 1),
  review_status text NOT NULL DEFAULT 'approved' CHECK (
    review_status IN ('candidate', 'approved', 'rejected', 'stale')
  ),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS compass.graph_retrieval_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id text,
  message_id text,
  query text NOT NULL,
  vendor_intent text[] NOT NULL DEFAULT '{}'::text[],
  query_terms text[] NOT NULL DEFAULT '{}'::text[],
  assertion_ids uuid[] NOT NULL DEFAULT '{}'::uuid[],
  retrieval_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS evidence_nodes_node_type_idx ON compass.evidence_nodes(node_type);
CREATE INDEX IF NOT EXISTS evidence_nodes_vendor_idx ON compass.evidence_nodes(vendor);
CREATE INDEX IF NOT EXISTS evidence_nodes_label_fts_idx
  ON compass.evidence_nodes
  USING gin (to_tsvector('simple', coalesce(label, '') || ' ' || coalesce(vendor, '')));

CREATE INDEX IF NOT EXISTS resolved_cases_status_idx ON compass.resolved_cases(resolution_status);
CREATE INDEX IF NOT EXISTS resolved_cases_approved_idx ON compass.resolved_cases(approved_for_retrieval);
CREATE INDEX IF NOT EXISTS resolved_cases_question_fts_idx
  ON compass.resolved_cases
  USING gin (to_tsvector('simple', coalesce(question, '') || ' ' || coalesce(issue_summary, '') || ' ' || coalesce(resolution_summary, '')));

CREATE INDEX IF NOT EXISTS evidence_assertions_vendor_idx ON compass.evidence_assertions(vendor);
CREATE INDEX IF NOT EXISTS evidence_assertions_source_kind_idx ON compass.evidence_assertions(source_kind);
CREATE INDEX IF NOT EXISTS evidence_assertions_review_status_idx ON compass.evidence_assertions(review_status);
CREATE INDEX IF NOT EXISTS evidence_assertions_source_chunk_idx ON compass.evidence_assertions(source_chunk_id);
CREATE INDEX IF NOT EXISTS evidence_assertions_case_idx ON compass.evidence_assertions(case_id);
CREATE INDEX IF NOT EXISTS evidence_assertions_claim_fts_idx
  ON compass.evidence_assertions
  USING gin (to_tsvector('simple', coalesce(claim_text, '') || ' ' || coalesce(excerpt, '') || ' ' || coalesce(vendor, '')));

CREATE INDEX IF NOT EXISTS evidence_edges_subject_idx ON compass.evidence_edges(subject_node_id);
CREATE INDEX IF NOT EXISTS evidence_edges_object_idx ON compass.evidence_edges(object_node_id);
CREATE INDEX IF NOT EXISTS evidence_edges_predicate_idx ON compass.evidence_edges(predicate);
CREATE INDEX IF NOT EXISTS evidence_edges_assertion_idx ON compass.evidence_edges(evidence_assertion_id);

ALTER TABLE compass.evidence_nodes ENABLE ROW LEVEL SECURITY;
ALTER TABLE compass.evidence_assertions ENABLE ROW LEVEL SECURITY;
ALTER TABLE compass.evidence_edges ENABLE ROW LEVEL SECURITY;
ALTER TABLE compass.resolved_cases ENABLE ROW LEVEL SECURITY;
ALTER TABLE compass.graph_retrieval_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Service role can manage evidence nodes" ON compass.evidence_nodes;
CREATE POLICY "Service role can manage evidence nodes"
  ON compass.evidence_nodes
  FOR ALL
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

DROP POLICY IF EXISTS "Authenticated users can view approved evidence nodes" ON compass.evidence_nodes;
CREATE POLICY "Authenticated users can view approved evidence nodes"
  ON compass.evidence_nodes
  FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "Service role can manage evidence assertions" ON compass.evidence_assertions;
CREATE POLICY "Service role can manage evidence assertions"
  ON compass.evidence_assertions
  FOR ALL
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

DROP POLICY IF EXISTS "Authenticated users can view approved evidence assertions" ON compass.evidence_assertions;
CREATE POLICY "Authenticated users can view approved evidence assertions"
  ON compass.evidence_assertions
  FOR SELECT
  TO authenticated
  USING (
    evidence_decision = 'verified'
    AND review_status = 'approved'
    AND (
      source_kind = 'official_doc'
      OR EXISTS (
        SELECT 1
        FROM compass.resolved_cases rc
        WHERE rc.id = evidence_assertions.case_id
          AND rc.approved_for_retrieval = true
          AND rc.resolution_status = 'resolved'
      )
    )
  );

DROP POLICY IF EXISTS "Service role can manage evidence edges" ON compass.evidence_edges;
CREATE POLICY "Service role can manage evidence edges"
  ON compass.evidence_edges
  FOR ALL
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

DROP POLICY IF EXISTS "Authenticated users can view approved evidence edges" ON compass.evidence_edges;
CREATE POLICY "Authenticated users can view approved evidence edges"
  ON compass.evidence_edges
  FOR SELECT
  TO authenticated
  USING (review_status = 'approved');

DROP POLICY IF EXISTS "Service role can manage resolved cases" ON compass.resolved_cases;
CREATE POLICY "Service role can manage resolved cases"
  ON compass.resolved_cases
  FOR ALL
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

DROP POLICY IF EXISTS "Authenticated users can view approved resolved cases" ON compass.resolved_cases;
CREATE POLICY "Authenticated users can view approved resolved cases"
  ON compass.resolved_cases
  FOR SELECT
  TO authenticated
  USING (approved_for_retrieval = true AND resolution_status = 'resolved');

DROP POLICY IF EXISTS "Service role can manage graph retrieval logs" ON compass.graph_retrieval_logs;
CREATE POLICY "Service role can manage graph retrieval logs"
  ON compass.graph_retrieval_logs
  FOR ALL
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

CREATE OR REPLACE FUNCTION compass.promote_learning_feedback_to_resolved_case(
  p_learning_feedback_id bigint,
  p_issue_summary text DEFAULT NULL,
  p_resolution_summary text DEFAULT NULL,
  p_vendor text DEFAULT NULL,
  p_claim_type text DEFAULT 'resolved_issue',
  p_reviewed_by text DEFAULT NULL
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = compass, public
AS $$
DECLARE
  feedback_row compass.learning_feedback%ROWTYPE;
  new_case_id uuid;
  final_issue_summary text;
  final_resolution_summary text;
  final_vendor text;
  final_claim_type text;
BEGIN
  SELECT *
    INTO feedback_row
    FROM compass.learning_feedback
   WHERE id = p_learning_feedback_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'learning_feedback % was not found', p_learning_feedback_id;
  END IF;

  final_issue_summary := NULLIF(trim(coalesce(p_issue_summary, feedback_row.question, '')), '');
  final_resolution_summary := NULLIF(trim(coalesce(p_resolution_summary, feedback_row.answer, '')), '');
  final_vendor := NULLIF(upper(trim(coalesce(p_vendor, feedback_row.learning_payload->>'sourceVendor', ''))), '');
  final_claim_type := coalesce(NULLIF(trim(p_claim_type), ''), 'resolved_issue');

  IF final_issue_summary IS NULL OR final_resolution_summary IS NULL THEN
    RAISE EXCEPTION 'issue_summary and resolution_summary are required';
  END IF;

  IF final_claim_type NOT IN (
    'definition',
    'requirement',
    'prohibition',
    'allowance',
    'limit',
    'procedure',
    'asset_spec',
    'resolved_issue',
    'risk',
    'setup_step'
  ) THEN
    RAISE EXCEPTION 'unsupported claim_type: %', final_claim_type;
  END IF;

  INSERT INTO compass.resolved_cases (
    conversation_id,
    message_id,
    feedback_id,
    question,
    issue_summary,
    resolution_summary,
    resolution_status,
    resolved_by,
    resolved_at,
    approved_for_retrieval,
    sources,
    metadata
  )
  VALUES (
    feedback_row.conversation_id,
    feedback_row.message_id,
    feedback_row.id,
    coalesce(feedback_row.question, final_issue_summary),
    final_issue_summary,
    final_resolution_summary,
    'resolved',
    p_reviewed_by,
    now(),
    true,
    coalesce(feedback_row.sources, '[]'::jsonb),
    jsonb_build_object(
      'learning_feedback_id', feedback_row.id,
      'feedback_key', feedback_row.feedback_key,
      'learning_target', feedback_row.learning_target,
      'promoted_by_function', 'promote_learning_feedback_to_resolved_case'
    )
  )
  RETURNING id INTO new_case_id;

  INSERT INTO compass.evidence_assertions (
    claim_text,
    claim_type,
    source_kind,
    case_id,
    excerpt,
    vendor,
    evidence_decision,
    confidence,
    review_status,
    metadata
  )
  VALUES (
    final_resolution_summary,
    final_claim_type,
    'resolved_case',
    new_case_id,
    final_issue_summary || E'\n\n' || final_resolution_summary,
    final_vendor,
    'verified',
    coalesce(feedback_row.confidence, 0.8),
    'approved',
    jsonb_build_object(
      'learning_feedback_id', feedback_row.id,
      'feedback_key', feedback_row.feedback_key,
      'question', feedback_row.question,
      'source_kind', 'resolved_case'
    )
  );

  UPDATE compass.learning_feedback
     SET learning_status = 'applied',
         reviewed_by = p_reviewed_by,
         reviewed_at = now(),
         applied_at = now(),
         learning_payload = jsonb_set(
           coalesce(learning_payload, '{}'::jsonb),
           '{resolved_case_id}',
           to_jsonb(new_case_id::text),
           true
         ),
         updated_at = now()
   WHERE id = p_learning_feedback_id;

  RETURN new_case_id;
END;
$$;

GRANT USAGE ON SCHEMA compass TO anon, authenticated, service_role;
GRANT SELECT ON TABLE compass.evidence_nodes TO authenticated;
GRANT SELECT ON TABLE compass.evidence_assertions TO authenticated;
GRANT SELECT ON TABLE compass.evidence_edges TO authenticated;
GRANT SELECT ON TABLE compass.resolved_cases TO authenticated;
GRANT ALL ON TABLE compass.evidence_nodes TO service_role;
GRANT ALL ON TABLE compass.evidence_assertions TO service_role;
GRANT ALL ON TABLE compass.evidence_edges TO service_role;
GRANT ALL ON TABLE compass.resolved_cases TO service_role;
GRANT ALL ON TABLE compass.graph_retrieval_logs TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA compass TO service_role;
REVOKE ALL ON FUNCTION compass.promote_learning_feedback_to_resolved_case(bigint, text, text, text, text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION compass.promote_learning_feedback_to_resolved_case(bigint, text, text, text, text, text) TO service_role;
