-- Compass answer durable cache and cross-instance runtime metrics.
-- The API remains fail-open: if these tables are unavailable, runtime falls back
-- to per-instance memory cache and metrics.

CREATE SCHEMA IF NOT EXISTS compass;

CREATE TABLE IF NOT EXISTS compass.answer_response_cache (
  cache_key text PRIMARY KEY,
  body jsonb NOT NULL,
  status integer NOT NULL DEFAULT 200 CHECK (status >= 100 AND status < 600),
  expires_at timestamptz NOT NULL,
  hit_count bigint NOT NULL DEFAULT 0,
  last_hit_at timestamptz,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS answer_response_cache_expires_at_idx
  ON compass.answer_response_cache (expires_at);

CREATE TABLE IF NOT EXISTS compass.answer_runtime_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type text NOT NULL DEFAULT 'request_completed' CHECK (
    event_type IN ('request_completed')
  ),
  cache_status text NOT NULL CHECK (cache_status IN ('HIT', 'MISS', 'BYPASS')),
  cache_key text,
  processing_time_ms integer,
  retrieval_duration_ms integer,
  answer_generation_duration_ms integer,
  retrieval_timed_out boolean NOT NULL DEFAULT false,
  retrieval_channel_timed_out boolean NOT NULL DEFAULT false,
  no_data_found boolean NOT NULL DEFAULT false,
  error_response boolean NOT NULL DEFAULT false,
  model text,
  source_count integer,
  graph_like_source_count integer,
  slowest_channel jsonb,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS answer_runtime_events_created_at_idx
  ON compass.answer_runtime_events (created_at DESC);

CREATE INDEX IF NOT EXISTS answer_runtime_events_cache_status_created_at_idx
  ON compass.answer_runtime_events (cache_status, created_at DESC);

CREATE INDEX IF NOT EXISTS answer_runtime_events_model_created_at_idx
  ON compass.answer_runtime_events (model, created_at DESC);

ALTER TABLE compass.answer_response_cache ENABLE ROW LEVEL SECURITY;
ALTER TABLE compass.answer_runtime_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Service role can manage answer response cache" ON compass.answer_response_cache;
CREATE POLICY "Service role can manage answer response cache"
  ON compass.answer_response_cache
  FOR ALL
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

DROP POLICY IF EXISTS "Service role can manage answer runtime events" ON compass.answer_runtime_events;
CREATE POLICY "Service role can manage answer runtime events"
  ON compass.answer_runtime_events
  FOR ALL
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

CREATE OR REPLACE FUNCTION compass.touch_answer_response_cache_hit(
  p_cache_key text
)
RETURNS void
LANGUAGE sql
SECURITY DEFINER
SET search_path = compass, public
AS $$
  UPDATE compass.answer_response_cache
     SET hit_count = hit_count + 1,
         last_hit_at = now(),
         updated_at = now()
   WHERE cache_key = p_cache_key;
$$;

CREATE OR REPLACE FUNCTION compass.prune_expired_answer_response_cache()
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = compass, public
AS $$
DECLARE
  affected integer := 0;
BEGIN
  DELETE FROM compass.answer_response_cache
   WHERE expires_at <= now();

  GET DIAGNOSTICS affected = ROW_COUNT;
  RETURN affected;
END;
$$;

CREATE OR REPLACE FUNCTION compass.get_answer_runtime_metrics(
  p_since timestamptz DEFAULT now() - interval '24 hours'
)
RETURNS jsonb
LANGUAGE sql
SECURITY DEFINER
SET search_path = compass, public
AS $$
  WITH recent AS (
    SELECT *
      FROM compass.answer_runtime_events
     WHERE created_at >= p_since
  ),
  latest AS (
    SELECT created_at, slowest_channel
      FROM recent
     ORDER BY created_at DESC
     LIMIT 1
  ),
  cache_entries AS (
    SELECT count(*)::integer AS active_count
      FROM compass.answer_response_cache
     WHERE expires_at > now()
  ),
  aggregate AS (
    SELECT
      count(*)::integer AS completed_request_count,
      count(*) FILTER (WHERE cache_status IN ('HIT', 'MISS'))::integer AS cacheable_request_count,
      count(*) FILTER (WHERE cache_status = 'HIT')::integer AS hit_count,
      count(*) FILTER (WHERE cache_status = 'MISS')::integer AS miss_count,
      count(*) FILTER (WHERE cache_status = 'BYPASS')::integer AS bypassed_request_count,
      count(*) FILTER (WHERE error_response)::integer AS error_response_count,
      count(*) FILTER (WHERE no_data_found)::integer AS no_data_response_count,
      count(*) FILTER (WHERE retrieval_timed_out OR retrieval_channel_timed_out)::integer AS retrieval_limited_response_count,
      round(avg(processing_time_ms))::integer AS avg_processing_time_ms,
      round(avg(retrieval_duration_ms) FILTER (WHERE cache_status <> 'HIT' AND retrieval_duration_ms IS NOT NULL))::integer AS avg_retrieval_duration_ms,
      round(avg(answer_generation_duration_ms) FILTER (WHERE cache_status <> 'HIT' AND answer_generation_duration_ms IS NOT NULL))::integer AS avg_answer_generation_duration_ms,
      count(retrieval_duration_ms) FILTER (WHERE cache_status <> 'HIT')::integer AS retrieval_sample_count,
      count(answer_generation_duration_ms) FILTER (WHERE cache_status <> 'HIT')::integer AS answer_generation_sample_count
    FROM recent
  )
  SELECT jsonb_build_object(
    'status', 'ready',
    'windowStart', p_since,
    'windowEnd', now(),
    'completedRequestCount', aggregate.completed_request_count,
    'cacheableRequestCount', aggregate.cacheable_request_count,
    'hitCount', aggregate.hit_count,
    'missCount', aggregate.miss_count,
    'bypassedRequestCount', aggregate.bypassed_request_count,
    'cacheHitRatio', CASE
      WHEN aggregate.cacheable_request_count > 0
        THEN round((aggregate.hit_count::numeric / aggregate.cacheable_request_count::numeric), 4)
      ELSE NULL
    END,
    'errorResponseCount', aggregate.error_response_count,
    'noDataResponseCount', aggregate.no_data_response_count,
    'retrievalLimitedResponseCount', aggregate.retrieval_limited_response_count,
    'avgProcessingTimeMs', aggregate.avg_processing_time_ms,
    'avgRetrievalDurationMs', aggregate.avg_retrieval_duration_ms,
    'avgAnswerGenerationDurationMs', aggregate.avg_answer_generation_duration_ms,
    'retrievalSampleCount', aggregate.retrieval_sample_count,
    'answerGenerationSampleCount', aggregate.answer_generation_sample_count,
    'lastEventAt', latest.created_at,
    'lastSlowestChannel', latest.slowest_channel,
    'cacheEntryCount', cache_entries.active_count
  )
  FROM aggregate
  CROSS JOIN cache_entries
  LEFT JOIN latest ON true;
$$;

GRANT USAGE ON SCHEMA compass TO anon, authenticated, service_role;
GRANT ALL ON TABLE compass.answer_response_cache TO service_role;
GRANT ALL ON TABLE compass.answer_runtime_events TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA compass TO service_role;
REVOKE ALL ON FUNCTION compass.touch_answer_response_cache_hit(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION compass.prune_expired_answer_response_cache() FROM PUBLIC;
REVOKE ALL ON FUNCTION compass.get_answer_runtime_metrics(timestamptz) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION compass.touch_answer_response_cache_hit(text) TO service_role;
GRANT EXECUTE ON FUNCTION compass.prune_expired_answer_response_cache() TO service_role;
GRANT EXECUTE ON FUNCTION compass.get_answer_runtime_metrics(timestamptz) TO service_role;
